[build]
# Default target — custom AArch64 bare metal
target = "kernel/aarch64-cantaya.json"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[target.aarch64-cantaya]
rustflags = ["-C", "link-arg=-T", "-C", "link-arg=kernel/linker.ld"]

[target.x86_64-cantaya]
rustflags = ["-C", "link-arg=-T", "-C", "link-arg=kernel/linker-x86_64.ld"]
