// Interrupt Descriptor Table (IDT)
//
// The IDT tells the CPU what function to call when an interrupt or exception occurs.
// Exceptions (0-31) are generated by the CPU itself (divide by zero, page fault, etc.)
// Hardware interrupts (32+) come from devices via the interrupt controller (PIC/APIC).
//
// Each IDT entry contains:
//   - Address of the handler function
//   - Code segment selector (which GDT entry to use)
//   - Gate type (interrupt gate disables interrupts, trap gate doesn't)
//   - DPL (minimum privilege level to trigger via INT instruction)
//   - IST index (optional separate stack for critical handlers)
//
// In Windows NT, the IDT is set up by the HAL and populated with trap handlers
// that dispatch to the kernel. We follow a similar pattern.

use core::cell::UnsafeCell;
use super::gdt::KERNEL_CODE_SELECTOR;

/// Number of IDT entries (256 is the max for x86_64)
const IDT_ENTRIES: usize = 256;

/// IDT entry (16 bytes)
#[repr(C, packed)]
#[derive(Clone, Copy)]
struct IdtEntry {
    offset_low: u16,    // Handler address bits 0..15
    selector: u16,      // GDT code segment selector
    ist: u8,            // Interrupt Stack Table index (0 = don't switch stack)
    type_attr: u8,      // Gate type, DPL, and present bit
    offset_mid: u16,    // Handler address bits 16..31
    offset_high: u32,   // Handler address bits 32..63
    _reserved: u32,
}

impl IdtEntry {
    /// Create a null/missing IDT entry
    const fn missing() -> Self {
        Self {
            offset_low: 0,
            selector: 0,
            ist: 0,
            type_attr: 0,
            offset_mid: 0,
            offset_high: 0,
            _reserved: 0,
        }
    }

    /// Create an interrupt gate entry.
    ///
    /// Interrupt gates automatically disable interrupts (clear IF) when entered.
    /// This prevents nested interrupts, which simplifies handler logic.
    fn interrupt_gate(handler: u64, ist_index: u8) -> Self {
        Self {
            offset_low: handler as u16,
            selector: KERNEL_CODE_SELECTOR,
            ist: ist_index,
            type_attr: 0b1000_1110, // Present, DPL=0, 64-bit Interrupt Gate
            offset_mid: (handler >> 16) as u16,
            offset_high: (handler >> 32) as u32,
            _reserved: 0,
        }
    }

    /// Create a trap gate entry (doesn't disable interrupts)
    fn trap_gate(handler: u64, ist_index: u8) -> Self {
        Self {
            offset_low: handler as u16,
            selector: KERNEL_CODE_SELECTOR,
            ist: ist_index,
            type_attr: 0b1000_1111, // Present, DPL=0, 64-bit Trap Gate
            offset_mid: (handler >> 16) as u16,
            offset_high: (handler >> 32) as u32,
            _reserved: 0,
        }
    }
}

/// IDT Descriptor (IDTR register value) — points to the IDT in memory
#[repr(C, packed)]
struct IdtDescriptor {
    size: u16,
    offset: u64,
}

/// The actual IDT table
#[repr(C, align(16))]
struct Idt {
    entries: [IdtEntry; IDT_ENTRIES],
}

// ---------------------------------------------------------------------------
// Safe wrapper — same pattern as GDT
// ---------------------------------------------------------------------------
#[repr(transparent)]
struct StaticCell<T>(UnsafeCell<T>);
unsafe impl<T> Sync for StaticCell<T> {}

impl<T> StaticCell<T> {
    const fn new(val: T) -> Self {
        Self(UnsafeCell::new(val))
    }
    #[allow(clippy::mut_from_ref)]
    unsafe fn get_mut(&self) -> &mut T {
        &mut *self.0.get()
    }
    fn as_ptr(&self) -> *const T {
        self.0.get()
    }
}

static IDT: StaticCell<Idt> = StaticCell::new(Idt {
    entries: [IdtEntry::missing(); IDT_ENTRIES],
});

/// Helper to load the IDT into the IDTR register.
unsafe fn load_idt() {
    let idt_descriptor = IdtDescriptor {
        size: (core::mem::size_of::<Idt>() - 1) as u16,
        offset: IDT.as_ptr() as u64,
    };
    core::arch::asm!(
        "lidt [{}]",
        in(reg) &idt_descriptor,
    );
}

/// Initialize the IDT with exception and interrupt handlers.
pub fn init() {
    unsafe {
        let idt = IDT.get_mut();

        // CPU Exceptions (vectors 0-31)
        idt.entries[0] = IdtEntry::interrupt_gate(divide_by_zero_handler as u64, 0);
        idt.entries[1] = IdtEntry::interrupt_gate(debug_handler as u64, 0);
        idt.entries[2] = IdtEntry::interrupt_gate(nmi_handler as u64, 0);
        idt.entries[3] = IdtEntry::trap_gate(breakpoint_handler as u64, 0);
        idt.entries[4] = IdtEntry::interrupt_gate(overflow_handler as u64, 0);
        idt.entries[5] = IdtEntry::interrupt_gate(bound_range_handler as u64, 0);
        idt.entries[6] = IdtEntry::interrupt_gate(invalid_opcode_handler as u64, 0);
        idt.entries[7] = IdtEntry::interrupt_gate(device_not_available_handler as u64, 0);
        idt.entries[8] = IdtEntry::interrupt_gate(double_fault_handler as u64, 1); // IST1 for safety
        // 9: Coprocessor Segment Overrun (legacy, not generated on modern CPUs)
        idt.entries[10] = IdtEntry::interrupt_gate(invalid_tss_handler as u64, 0);
        idt.entries[11] = IdtEntry::interrupt_gate(segment_not_present_handler as u64, 0);
        idt.entries[12] = IdtEntry::interrupt_gate(stack_segment_handler as u64, 1); // IST1 for safety
        idt.entries[13] = IdtEntry::interrupt_gate(general_protection_handler as u64, 0);
        idt.entries[14] = IdtEntry::interrupt_gate(page_fault_handler as u64, 0);
        // 15: Reserved
        idt.entries[16] = IdtEntry::interrupt_gate(x87_fpu_handler as u64, 0);
        idt.entries[17] = IdtEntry::interrupt_gate(alignment_check_handler as u64, 0);
        idt.entries[18] = IdtEntry::interrupt_gate(machine_check_handler as u64, 1); // IST1
        idt.entries[19] = IdtEntry::interrupt_gate(simd_fp_handler as u64, 0);

        // Hardware interrupts (remapped PIC: IRQ0-15 → vectors 32-47)
        idt.entries[32] = IdtEntry::interrupt_gate(timer_handler as u64, 0);      // IRQ0: PIT Timer
        idt.entries[33] = IdtEntry::interrupt_gate(keyboard_handler as u64, 0);   // IRQ1: Keyboard
        idt.entries[44] = IdtEntry::interrupt_gate(mouse_handler as u64, 0);      // IRQ12: PS/2 Mouse

        // Load the IDT
        load_idt();
    }
}

// ============================================================================
// Interrupt/Exception Stack Frame
// ============================================================================

/// The stack frame pushed by the CPU on an interrupt/exception
#[repr(C)]
#[derive(Debug)]
struct InterruptStackFrame {
    instruction_pointer: u64,
    code_segment: u64,
    cpu_flags: u64,
    stack_pointer: u64,
    stack_segment: u64,
}

// ============================================================================
// Exception Handlers
// ============================================================================

/// Macro to create an exception handler that saves all registers,
/// calls a Rust function, then restores registers and returns via IRETQ.
macro_rules! exception_handler {
    ($name:ident, $handler_fn:ident) => {
        #[unsafe(naked)]
        unsafe extern "C" fn $name() {
            core::arch::naked_asm!(
                "push rax", "push rbx", "push rcx", "push rdx",
                "push rsi", "push rdi", "push rbp",
                "push r8",  "push r9",  "push r10", "push r11",
                "push r12", "push r13", "push r14", "push r15",
                "lea rdi, [rsp + 15*8]",
                "call {handler}",
                "pop r15", "pop r14", "pop r13", "pop r12",
                "pop r11", "pop r10", "pop r9",  "pop r8",
                "pop rbp", "pop rdi", "pop rsi",
                "pop rdx", "pop rcx", "pop rbx", "pop rax",
                "iretq",
                handler = sym $handler_fn,
            );
        }
    };
}

/// Macro for exception handlers that have an error code pushed by the CPU
macro_rules! exception_handler_with_error {
    ($name:ident, $handler_fn:ident) => {
        #[unsafe(naked)]
        unsafe extern "C" fn $name() {
            core::arch::naked_asm!(
                "push rax", "push rbx", "push rcx", "push rdx",
                "push rsi", "push rdi", "push rbp",
                "push r8",  "push r9",  "push r10", "push r11",
                "push r12", "push r13", "push r14", "push r15",
                "mov rsi, [rsp + 15*8]",
                "lea rdi, [rsp + 16*8]",
                "call {handler}",
                "pop r15", "pop r14", "pop r13", "pop r12",
                "pop r11", "pop r10", "pop r9",  "pop r8",
                "pop rbp", "pop rdi", "pop rsi",
                "pop rdx", "pop rcx", "pop rbx", "pop rax",
                "add rsp, 8",
                "iretq",
                handler = sym $handler_fn,
            );
        }
    };
}

// Generate handler stubs
exception_handler!(divide_by_zero_handler, handle_divide_by_zero);
exception_handler!(debug_handler, handle_debug);
exception_handler!(nmi_handler, handle_nmi);
exception_handler!(breakpoint_handler, handle_breakpoint);
exception_handler!(overflow_handler, handle_overflow);
exception_handler!(bound_range_handler, handle_bound_range);
exception_handler!(invalid_opcode_handler, handle_invalid_opcode);
exception_handler!(device_not_available_handler, handle_device_not_available);
exception_handler_with_error!(double_fault_handler, handle_double_fault);
exception_handler_with_error!(invalid_tss_handler, handle_invalid_tss);
exception_handler_with_error!(segment_not_present_handler, handle_segment_not_present);
exception_handler_with_error!(stack_segment_handler, handle_stack_segment);
exception_handler_with_error!(general_protection_handler, handle_general_protection);
exception_handler_with_error!(page_fault_handler, handle_page_fault);
exception_handler!(x87_fpu_handler, handle_x87_fpu);
exception_handler_with_error!(alignment_check_handler, handle_alignment_check);
exception_handler!(machine_check_handler, handle_machine_check);
exception_handler!(simd_fp_handler, handle_simd_fp);
exception_handler!(keyboard_handler, handle_keyboard);
exception_handler!(mouse_handler, handle_mouse);
exception_handler!(virtio_handler, handle_virtio);

// Timer handler — custom naked stub for context switching.
#[unsafe(naked)]
unsafe extern "C" fn timer_handler() {
    core::arch::naked_asm!(
        "push rax", "push rbx", "push rcx", "push rdx",
        "push rsi", "push rdi", "push rbp",
        "push r8",  "push r9",  "push r10", "push r11",
        "push r12", "push r13", "push r14", "push r15",
        "mov rdi, rsp",
        "call {handler}",
        "mov rsp, rax",
        "pop r15", "pop r14", "pop r13", "pop r12",
        "pop r11", "pop r10", "pop r9",  "pop r8",
        "pop rbp", "pop rdi", "pop rsi",
        "pop rdx", "pop rcx", "pop rbx", "pop rax",
        "iretq",
        handler = sym handle_timer_switch,
    );
}

// ============================================================================
// Rust Exception Handler Functions
// ============================================================================

extern "C" fn handle_divide_by_zero(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: Divide by Zero at {:#X}", frame.instruction_pointer);
    halt_loop();
}

extern "C" fn handle_debug(frame: &InterruptStackFrame) {
    log::debug!("EXCEPTION: Debug at {:#X}", frame.instruction_pointer);
}

extern "C" fn handle_nmi(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: Non-Maskable Interrupt at {:#X}", frame.instruction_pointer);
}

extern "C" fn handle_breakpoint(frame: &InterruptStackFrame) {
    log::info!("EXCEPTION: Breakpoint at {:#X}", frame.instruction_pointer);
}

extern "C" fn handle_overflow(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: Overflow at {:#X}", frame.instruction_pointer);
    halt_loop();
}

extern "C" fn handle_bound_range(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: Bound Range Exceeded at {:#X}", frame.instruction_pointer);
    halt_loop();
}

extern "C" fn handle_invalid_opcode(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: Invalid Opcode at {:#X}", frame.instruction_pointer);
    halt_loop();
}

extern "C" fn handle_device_not_available(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: Device Not Available at {:#X}", frame.instruction_pointer);
    halt_loop();
}

extern "C" fn handle_double_fault(frame: &InterruptStackFrame, error_code: u64) {
    log::error!(
        "EXCEPTION: Double Fault (error={:#X}) at {:#X}",
        error_code, frame.instruction_pointer
    );
    halt_loop();
}

extern "C" fn handle_general_protection(frame: &InterruptStackFrame, error_code: u64) {
    log::error!(
        "EXCEPTION: General Protection Fault (error={:#X}) at {:#X}",
        error_code, frame.instruction_pointer
    );
    halt_loop();
}

extern "C" fn handle_page_fault(frame: &InterruptStackFrame, error_code: u64) {
    let faulting_addr = super::cpu::read_cr2();
    log::error!(
        "EXCEPTION: Page Fault accessing {:#X} (error={:#X}) at {:#X}",
        faulting_addr, error_code, frame.instruction_pointer
    );
    log::error!(
        "  Flags: {} {} {} {}",
        if error_code & 1 != 0 { "PROTECTION" } else { "NOT_PRESENT" },
        if error_code & 2 != 0 { "WRITE" } else { "READ" },
        if error_code & 4 != 0 { "USER" } else { "KERNEL" },
        if error_code & 16 != 0 { "INSTRUCTION_FETCH" } else { "" },
    );
    halt_loop();
}

extern "C" fn handle_invalid_tss(frame: &InterruptStackFrame, error_code: u64) {
    log::error!(
        "EXCEPTION: Invalid TSS (selector={:#X}) at {:#X}",
        error_code, frame.instruction_pointer
    );
    halt_loop();
}

extern "C" fn handle_segment_not_present(frame: &InterruptStackFrame, error_code: u64) {
    log::error!(
        "EXCEPTION: Segment Not Present (selector={:#X}) at {:#X}",
        error_code, frame.instruction_pointer
    );
    halt_loop();
}

extern "C" fn handle_stack_segment(frame: &InterruptStackFrame, error_code: u64) {
    log::error!(
        "EXCEPTION: Stack-Segment Fault (error={:#X}) at {:#X}",
        error_code, frame.instruction_pointer
    );
    halt_loop();
}

extern "C" fn handle_x87_fpu(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: x87 FPU Error at {:#X}", frame.instruction_pointer);
    halt_loop();
}

extern "C" fn handle_alignment_check(frame: &InterruptStackFrame, error_code: u64) {
    log::error!(
        "EXCEPTION: Alignment Check (error={:#X}) at {:#X}",
        error_code, frame.instruction_pointer
    );
    halt_loop();
}

extern "C" fn handle_machine_check(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: Machine Check — hardware failure at {:#X}", frame.instruction_pointer);
    halt_loop();
}

extern "C" fn handle_simd_fp(frame: &InterruptStackFrame) {
    log::error!("EXCEPTION: SIMD Floating-Point at {:#X}", frame.instruction_pointer);
    halt_loop();
}

/// Timer ISR dispatcher — handles scheduling and tick accounting.
extern "C" fn handle_timer_switch(saved_rsp: u64) -> u64 {
    let new_rsp = crate::core_kernel::scheduler::timer_tick(saved_rsp);
    crate::shell::timer_tick();
    unsafe { super::port::outb(0x20, 0x20); }
    new_rsp
}

extern "C" fn handle_keyboard(_frame: &InterruptStackFrame) {
    let scancode = unsafe { super::port::inb(0x60) };
    super::keyboard::handle_scancode(scancode);
    crate::shell::keyboard_irq();
    unsafe { super::port::outb(0x20, 0x20); }
}

extern "C" fn handle_mouse(_frame: &InterruptStackFrame) {
    super::mouse::handle_irq();
    unsafe {
        super::port::outb(0xA0, 0x20);
        super::port::outb(0x20, 0x20);
    }
}

extern "C" fn handle_virtio(_frame: &InterruptStackFrame) {
    super::virtio_blk::handle_interrupt();
    super::virtio_net::handle_interrupt();
    unsafe {
        super::port::outb(0xA0, 0x20);
        super::port::outb(0x20, 0x20);
    }
}

/// Halt the CPU forever (used after unrecoverable exceptions)
fn halt_loop() -> ! {
    loop {
        unsafe { core::arch::asm!("cli; hlt"); }
    }
}

/// Register the virtio interrupt handler at the given IRQ vector.
///
/// Called at runtime once the PCI interrupt line is known.
pub fn register_virtio_irq(irq: u8) {
    if irq >= 16 {
        log::warn!("IDT: invalid IRQ {} for virtio handler", irq);
        return;
    }
    let vector = 32 + irq as usize;
    unsafe {
        let idt = IDT.get_mut();
        idt.entries[vector] = IdtEntry::interrupt_gate(virtio_handler as u64, 0);
        load_idt();
    }
    log::info!("IDT: registered virtio handler at vector {} (IRQ {})", vector, irq);
}
